language: objective-c
osx_image: xcode9.2
xcode_project: Blog-integration.xcworkspace
xcode_scheme: Blog-integration

before_install:

- gem install xcpretty -N --no-ri --no-rdoc

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace Blog-integration.xcworkspace -scheme Blog-integration CODE_SIGNING_REQUIRED=NO | xcpretty && xcodebuild test -sdk iphonesimulator -workspace Blog-integration.xcworkspace -destination "platform=iOS Simulator,name=iPhone 7" -scheme Blog-integration CODE_SIGNING_REQUIRED=NO | xcpretty
